### PR TITLE
[PPP-4174] Use classes from data-access when processing responses from

### PR DESCRIPTION
**Pull request by peterrinehart**
metadataDA service.

### CODE REVIEW

**Comment by buildguy** [comment]
[comment]: <> (FrogbotReviewComment)

<div align='center'>

[👍 Frogbot scanned this pull request and did not find any new security issues.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>



---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :warning: Build finished in 8m 47s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 3 test(s) failed:

<details><summary><b>org.pentaho.platform.dataaccess.ConditionTest.testGetConditionWithoutParametersForAllDataTypes</b> (click to expand)</summary><p>

```
Cannot load from object array because "value" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.dataaccess.ConditionTest.testGetConditionWithParametersForAllDataTypes</b> (click to expand)</summary><p>

```
Cannot load from object array because "value" is null
```

</p></details>

<details><summary><b>org.pentaho.platform.dataaccess.metadata.service.MetadataServiceTest.testLoadModelJson</b> (click to expand)</summary><p>

```
expected:<...gory","columns":[],"[]id":"CATEGORY_ID","n...> but was:<...gory","columns":[],"[description":null,"]id":"CATEGORY_ID","n...>
```

</p></details>

  
Tests run: **361**, Failures: **3**, Skipped: **1** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/data-access-plugin/job/PR-1282/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
[comment]: <> (FrogbotReviewComment)

<div align='center'>

[👍 Frogbot scanned this pull request and did not find any new security issues.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>



---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 10m 39s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **361**, Failures: **0**, Skipped: **1** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/data-access-plugin/job/PR-1282/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by ddiroma — APPROVED** [review]

**Pull request merged**
