### PR TITLE
[BISERVER-10319] implemented an option of loading metadata as DSW

### PR DESCRIPTION
**Pull request by stepanovdg**

### CODE REVIEW

**Comment by stepanovdg** [comment]
@mchen-len-son @pamval, @mbatchelor, Could you please take a look?

**Comment by pamval** [comment]
@stepanovdg are you sure this compiles? Even fixing the merge conflicts, I get a compilation error locally and that is usually the cause for wingman reporting 100% coverage drop in all files.

**Comment by stepanovdg** [comment]
@pamval I see now I will update pull-request. At the moment I sent it - it compiles and worked correctly  - even wingman succeed. - Only coverage was less. Will recheck and update pull-request maybe some new changes made it incorrect.

**Comment by stepanovdg** [comment]
@pamval I updated pull-request with resolved conflicts. 

The problem with compilation relates to https://github.com/pentaho/pentaho-platform/pull/3657/files#diff-26b64b3cbf64fb684a10bc4574be7455R185 

This issue has two pull-requests and this one depends on https://github.com/pentaho/pentaho-platform/pull/3657 

So you need to build that one first and publish artifacts to local repo to use them in current pull-request

**Comment by pamval** [comment]
@stepanovdg I'm getting two failed tests while compiling these changes locally:

Tests in error: 
  DataSourceWizardServiceTest.testPublishDswFromTemp:345 » FileNotFound test.xmi...
  MetadataServiceTest.testIsContainsModel:445->testIsContainsModel:451 » FileNotFound

**Comment by pamval** [comment]
@stepanovdg there's a significant coverage drop in MetadataService, DataSourceWizardResource and MetadataResource. Can you review?

**Comment by stepanovdg** [comment]
@pamval I updated pull-request with tests for the all main functionality.

**Comment by kolinus** [comment]
@rmansoor @pedrofvteixeira  could you please take a look

**Pull request merged**
