### PR TITLE
BACKLOG-8297 -- DEV: identify base schema and annotations in the zip

### PR DESCRIPTION
**Pull request by kolinus**
What was done:
1) added logic for etracting schema and annotations from the bundle
2) added logic to import extracted schema

### CODE REVIEW

**Comment by kolinus** [comment]
@pminutillo @kurtwalker could you please review

**Comment by kurtwalker** [comment]
@kolinus doesn't look like we're doing anything with the annotations.xml.  Is that part still a WIP?

**Comment by kolinus** [comment]
@kurtwalker the backlog is about identifying both schema and annotations. 
there is another backlog for applying annotations

**Comment by kurtwalker** [comment]
ok

**Pull request merged**
