### PR TITLE
[TEST] - fix test

### PR DESCRIPTION
**Pull request by aliakseihaidukou**
now every project has it's own repo path

### CODE REVIEW

**Comment by dkincade** [comment]
@mdamour1976 @e-cuellar please review ...

**Comment by e-cuellar** [comment]
@aliakseihaidukou Is this test passing in both Windows and Linux?...  The path "/tmp/data-access/jackrabbit-test-TRUNK" seems to be very Linux dependent....

**Comment by aliakseihaidukou** [comment]
@e-cuellar tested with Windows 7 64x

**Comment by e-cuellar** [comment]
@aliakseihaidukou And it passes to me locally to so I believe we are good to go!

**Pull request merged**
