### PR TITLE
[BACKLOG-4725] - introducing parameter for import called retainInline…

### PR DESCRIPTION
**Pull request by kurtwalker**
…Annotations.  by default import with overwrite will remove the existing catalog first, which removes the annotations.  Use the new parameter to prevent removal of catalog which retains the inline annotations.  Also refactoring tests in AnalysisServiceTest because they weren't testing anything.

### CODE REVIEW

**Comment by kurtwalker** [comment]
@bytekast @pminutillo @DFieldFL

**Comment by DFieldFL** [comment]
:+1:

**Comment by kurtwalker** [comment]
I supposed I should've said, please merge

**Comment by DFieldFL** [comment]
sorry I wanted a second set of eyes to look at it. Mainly Rowell since he knows more of what is going on in this code.

**Comment by bytekast** [comment]
there must've been a bug in my "pull request automation rules"... this should've been auto-merged lol

**Comment by kurtwalker** [comment]
haha, np

**Pull request merged**
