### PR TITLE
[PPP-4947] - When exporting a JDBC connection using API the password gets assigned a null value it cannot be reused anywhere else

### PR DESCRIPTION
**Pull request by bcostahitachivantara**

### CODE REVIEW

**Comment by buildguy** [comment]
### :warning: Build finished in 10m 50s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
assemblies/data-access-plugin,core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.platform.dataaccess.datasource.api.resources.JDBCDatasourceResourceTest.testGetConnection</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **359**, Failures: **1**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/data-access-plugin/job/PR-1228/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by smmribeiro — APPROVED** [review]
Looks good!

**Comment by buildguy** [comment]
### :warning: Build finished in 10m 12s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
assemblies/data-access-plugin,core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.platform.dataaccess.datasource.api.resources.JDBCDatasourceResourceTest.testGetConnection</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **359**, Failures: **1**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/data-access-plugin/job/PR-1228/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by renato-s — APPROVED** [review]

**Comment by bcostahitachivantara** [comment]
The JDBCDatasourceResourceTest.testGetConnection test is failing but seems not related with changes in my PR but with Powermockito/Mockito library.

**Pull request merged**
