### PR TITLE
[TEST] Added more unit tests for Condition class

### PR DESCRIPTION
**Pull request by rcanuto**
- Refactored Condition.java
   - Change Condition class code on method getCondition, to stop passing
     the value of the property "this.value" by reference

### CODE REVIEW

**Comment by rcanuto** [comment]
@pedrofvteixeira, @rmansoor please review

**Comment by pedrofvteixeira** [comment]
As far as unit tests go, all's well.
@pminutillo: your thoughts/concerns on the change done @ Condition.java ?

**Comment by pminutillo** [comment]
@pedrofvteixeira I think this looks ok if the intent is to avoid changing the original array values which seems to be the case

**Comment by pedrofvteixeira** [comment]
Thanks @pminutillo, @rmansoor; 
Merging PR.

**Pull request merged**
