### PR TITLE
BACKLOG-8299 - DEV: save annotations if they are present

### PR DESCRIPTION
**Pull request by kolinus**
What was done:
1) added import of annotations file

### CODE REVIEW

**Comment by kolinus** [comment]
@kurtwalker @rfellows could you please review. The changes are covered by tests from previous commit

**Comment by kolinus** [comment]
got different results for tests when running locally
will revisit

**Comment by kurtwalker** [comment]
"The changes are covered by tests from previous commit"
That statement can never be true.

**Comment by kolinus** [comment]
updated PR, waiting for wingman

**Comment by kolinus** [comment]
@kurtwalker @rfellows added tests, updated pr, waiting for wingman

**Comment by kolinus** [comment]
@kurtwalker  @rfellows could you please review.? The functionality is covered by integration tests

**Pull request merged**
