### PR TITLE
[BACKLOG-12037] - Mavenize data-access

### PR DESCRIPTION
**Pull request by rfellows**

### CODE REVIEW

**Comment by rfellows** [comment]
@smaring please review

**Comment by lgrill-pentaho** [comment]
The gwt pom is using the wrong artifact-id for the data-access core sources, it needs to be this:

      <artifactId>pentaho-bi-platform-data-access</artifactId>

**Comment by rfellows** [comment]
@lgrill-pentaho updated

**Comment by lgrill-pentaho** [comment]
Looks good now based on local build. Next step will be incorporation in test suite build.

**Pull request merged**
