### PR TITLE
[BISERVER-12829] Errors when integrating Pentaho User Console into an…

### PR DESCRIPTION
**Pull request by SergeyTravin**
… IFrame. changes for menu bar.

- change javascript for menu data access bar item

### CODE REVIEW

**Comment by SergeyTravin** [comment]
@mdamour1976 could you review it please?

**Comment by mdamour1976** [comment]
@SergeyTravin I presume it still works when you're in normal non-integrated iframe mode?

**Comment by SergeyTravin** [comment]
@mdamour1976, I have rechecked a behavior. It is still works in normal mode.

**Comment by pamval** [comment]
@mdamour1976 please recheck this pull request

**Pull request merged**
