### PR TITLE
[BISERVER-13024] - Oracle repository: unable to create CSV Data Sourc…

### PR DESCRIPTION
**Pull request by mchen-len-son**
…e (5.4)

- fixed table name specifying when dropping
- fixed unit test

### CODE REVIEW

**Comment by mchen-len-son** [comment]
@pamval, @pedrofvteixeira, run WM for the PR please

**Comment by lucboudreau** [comment]
http://10.100.11.222:8080/job/wingman-osgi/63/

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f build.xml jacoco-integration checkstyle

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove



Changed files:
==============
  src/org/pentaho/platform/dataaccess/datasource/wizard/service/agile/StagingTransformGenerator.java
  test-src/org/pentaho/platform/dataaccess/datasource/wizard/service/agile/StagingTransformGeneratorTest.java



Unit test coverage change:
============
org.pentaho.platform.dataaccess.datasource.wizard.service.agile.StagingTransformGenerator:
 * Instruction Change :  + .14%
 * Line Change :  + .25%



Integration test coverage change:
============
org.pentaho.platform.dataaccess.datasource.wizard.service.agile.StagingTransformGenerator:
 * Instruction Change :  + .06%
 * Line Change :  + .11%

**Comment by mchen-len-son** [comment]
@akhayrutdinov review please

**Pull request merged**
