### PR TITLE
[BACKLOG-39432] Add the option to choose traditional Chinese language…

### PR DESCRIPTION
**Pull request by eddie-martinez**
… in PDI and PUC

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 16m 12s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
assemblies/data-access-plugin,core
```
---
:ok_hand: All tests passed!
 
Tests run: **361**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/data-access-plugin/job/PR-1245/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 19m 24s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
assemblies/data-access-plugin,core
```
---
:ok_hand: All tests passed!
 
Tests run: **361**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/data-access-plugin/job/PR-1245/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 18m 28s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
assemblies/data-access-plugin,core
```
---
:ok_hand: All tests passed!
 
Tests run: **361**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/data-access-plugin/job/PR-1245/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 16m 4s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
assemblies/data-access-plugin,core
```
---
:ok_hand: All tests passed!
 
Tests run: **361**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/data-access-plugin/job/PR-1245/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by ddiroma — APPROVED** [review]

**Pull request merged**
