### PR TITLE
[Biserver-12815] - Manage Data Sources: User can import an .xmi using "Import Analysis"

### PR DESCRIPTION
**Pull request by YuryBY**
@mdamour1976, @rmansoo, @e-cuellar, @pentaho-nbaker would you mind of reviewing/merging?

Here is platform's part: https://github.com/pentaho/pentaho-platform/pull/2929

### CODE REVIEW

**Comment by YuryBY** [comment]
@mdamour1976, @rmansoo, @e-cuellar the Platform's part has already merged: https://github.com/pentaho/pentaho-platform/pull/2939

**Comment by YuryBY** [comment]
@mdamour1976, @rmansoo, @e-cuellar @pamval, any updates?

**Comment by pamval** [comment]
@kurtwalker can you please review this pull request ?

thanks

**Comment by kurtwalker** [comment]
I thought we had decided not to use filename as a restriction.  Maybe I missed a conversation?

**Comment by YuryBY** [comment]
@kurtwalker, @pamval, this PR makes sanity check for null and .xmi files and does not break scenarios of  http://jira.pentaho.com/browse/BISERVER-12815. This was done in order to find mistake as soon as possible and do not parse the file. But PR can be safely closed since here is handling of parse exception: https://github.com/pentaho/pentaho-platform/pull/2939.

**Pull request merged**
