### PR TITLE
[BACKLOG-38108] In new data base connection window for Interactive report the other options for this connection are not visible

### PR DESCRIPTION
**Pull request by varuntangirala**
@Pentaho/wcag, please review

### CODE REVIEW

**Comment by buildguy** [comment]
### :warning: Build finished in 9m 20s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 3 test(s) failed:

<details><summary><b>org.pentaho.platform.dataaccess.DatasourceServiceHelperTest.testCsvDoesNotExist</b> (click to expand)</summary><p>

```
Could not initialize class org.pentaho.di.core.vfs.KettleVFS
```

</p></details>

<details><summary><b>org.pentaho.platform.dataaccess.DatasourceServiceHelperTest.testCsvSampleData</b> (click to expand)</summary><p>

```
Could not initialize class org.pentaho.di.core.vfs.KettleVFS
```

</p></details>

<details><summary><b>org.pentaho.platform.dataaccess.datasource.wizard.service.agile.StagingTransformGeneratorTest.org.pentaho.platform.dataaccess.datasource.wizard.service.agile.StagingTransformGeneratorTest</b> (click to expand)</summary><p>

```
org/apache/commons/lang3/ArrayUtils
```

</p></details>

  
Tests run: **358**, Failures: **3**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/data-access-plugin/job/PR-1216/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 10m 42s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **359**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/data-access-plugin/job/PR-1216/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by hv-vamsi — APPROVED** [review]

**Comment by buildguy** [comment]
### :warning: Build finished in 9m 52s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 3 test(s) failed:

<details><summary><b>org.pentaho.platform.dataaccess.DatasourceServiceHelperTest.testCsvDoesNotExist</b> (click to expand)</summary><p>

```
Could not initialize class org.pentaho.di.core.vfs.KettleVFS
```

</p></details>

<details><summary><b>org.pentaho.platform.dataaccess.DatasourceServiceHelperTest.testCsvSampleData</b> (click to expand)</summary><p>

```
Could not initialize class org.pentaho.di.core.vfs.KettleVFS
```

</p></details>

<details><summary><b>org.pentaho.platform.dataaccess.datasource.wizard.service.agile.StagingTransformGeneratorTest.org.pentaho.platform.dataaccess.datasource.wizard.service.agile.StagingTransformGeneratorTest</b> (click to expand)</summary><p>

```
org/apache/commons/lang3/ArrayUtils
```

</p></details>

  
Tests run: **358**, Failures: **3**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/data-access-plugin/job/PR-1216/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 9m 55s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 3 test(s) failed:

<details><summary><b>org.pentaho.platform.dataaccess.DatasourceServiceHelperTest.testCsvDoesNotExist</b> (click to expand)</summary><p>

```
Could not initialize class org.pentaho.di.core.vfs.KettleVFS
```

</p></details>

<details><summary><b>org.pentaho.platform.dataaccess.DatasourceServiceHelperTest.testCsvSampleData</b> (click to expand)</summary><p>

```
Could not initialize class org.pentaho.di.core.vfs.KettleVFS
```

</p></details>

<details><summary><b>org.pentaho.platform.dataaccess.datasource.wizard.service.agile.StagingTransformGeneratorTest.org.pentaho.platform.dataaccess.datasource.wizard.service.agile.StagingTransformGeneratorTest</b> (click to expand)</summary><p>

```
org/apache/commons/lang3/ArrayUtils
```

</p></details>

  
Tests run: **358**, Failures: **3**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/data-access-plugin/job/PR-1216/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
