### PR TITLE
[BACKLOG-36722] Fixed a11y issues for CSV dialog

### PR DESCRIPTION
**Pull request by AAravind27**
cherry-pick of https://github.com/pentaho/data-access/pull/1198  to master.
Dependent on https://github.com/pentaho/pentaho-commons-xul/pull/241

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 2m 5s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 1m 57s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Review by hv-vamsi — APPROVED** [review]

**Review by phalguni-a — APPROVED** [review]

**Comment by AAravind27** [comment]
The build is failing because it is dependent on PR (https://github.com/pentaho/pentaho-commons-xul/pull/241 ) and should be successful when  https://github.com/pentaho/pentaho-commons-xul/pull/241 is merged.

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 8m 32s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **359**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/data-access-plugin/job/PR-1200/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
