### PR TITLE
[BACKLOG-19296] - DSW - Error when importing CSV files with some spec…

### PR DESCRIPTION
**Pull request by Aliaksandr-Kastenka**
…ial character

### CODE REVIEW

**Comment by kurtwalker** [comment]
no way to unit test?

**Comment by Aliaksandr-Kastenka** [comment]
@kurtwalker  Currently we don't have a test for FileImportController

**Comment by kurtwalker** [comment]
I know...is there anything blocking us from writing one?

**Comment by kurtwalker** [comment]
we aren't set up for testing gwt controller classes

**Pull request merged**
