### PR TITLE
[BACKLOG-35298] CSRF - ImportDialog should specify the CSRF token as a form parameter

### PR DESCRIPTION
**Pull request by dcleao**
Depends on: https://github.com/pentaho/pentaho-platform/pull/4942.

See PR set: https://github.com/pentaho/security-web/pull/10.

@bennychow, @ddiroma please review and merge.

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 1m 9s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Review by bennychow — APPROVED** [review]

**Comment by dcleao** [comment]
@bennychow @ddiroma Hi folks, I noticed a class which is currently unused, but which is also calling the `/UploadService`. It's better to leave it updated to send the CSRF token, just in case.

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 6m 35s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **344**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.pentaho.net/job/projects/job/data-access-plugin/job/PR-1119/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by bennychow** [comment]
@dcleao Looks good to me.  The origin of that file pre-dates 4.0.

**Pull request merged**
