### PR TITLE
[BACKLOG-38108] In new data base connection window for Interactive report the other options for this connection are not visible

### PR DESCRIPTION
**Pull request by varuntangirala**
@pentaho/wcag Please review
This PR is part of https://github.com/pentaho/pentaho-commons-database/pull/236

### CODE REVIEW

**Comment by buildguy** [comment]
### :warning: Build finished in 9m 34s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 3 test(s) failed:

<details><summary><b>org.pentaho.platform.dataaccess.DatasourceServiceHelperTest.testCsvDoesNotExist</b> (click to expand)</summary><p>

```
Could not initialize class org.pentaho.di.core.vfs.KettleVFS
```

</p></details>

<details><summary><b>org.pentaho.platform.dataaccess.DatasourceServiceHelperTest.testCsvSampleData</b> (click to expand)</summary><p>

```
Could not initialize class org.pentaho.di.core.vfs.KettleVFS
```

</p></details>

<details><summary><b>org.pentaho.platform.dataaccess.datasource.wizard.service.agile.StagingTransformGeneratorTest.org.pentaho.platform.dataaccess.datasource.wizard.service.agile.StagingTransformGeneratorTest</b> (click to expand)</summary><p>

```
org/apache/commons/lang3/ArrayUtils
```

</p></details>

  
Tests run: **358**, Failures: **3**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/data-access-plugin/job/PR-1215/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by dcleao — APPROVED** [review]

**Review by hv-vamsi — APPROVED** [review]

**Comment by varuntangirala** [comment]
Checkout out to WCAG branch and ran the build in local. These test cases are failing without these changes as well

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 9m 34s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
:ok_hand: All tests passed!
 
Tests run: **359**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/data-access-plugin/job/PR-1215/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 9m 23s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
:ok_hand: All tests passed!
 
Tests run: **359**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/data-access-plugin/job/PR-1215/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 11m 15s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 3 test(s) failed:

<details><summary><b>org.pentaho.platform.dataaccess.DatasourceServiceHelperTest.testCsvDoesNotExist</b> (click to expand)</summary><p>

```
Could not initialize class org.pentaho.di.core.vfs.KettleVFS
```

</p></details>

<details><summary><b>org.pentaho.platform.dataaccess.DatasourceServiceHelperTest.testCsvSampleData</b> (click to expand)</summary><p>

```
Could not initialize class org.pentaho.di.core.vfs.KettleVFS
```

</p></details>

<details><summary><b>org.pentaho.platform.dataaccess.datasource.wizard.service.agile.StagingTransformGeneratorTest.org.pentaho.platform.dataaccess.datasource.wizard.service.agile.StagingTransformGeneratorTest</b> (click to expand)</summary><p>

```
org/apache/commons/lang3/ArrayUtils
```

</p></details>

  
Tests run: **358**, Failures: **3**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/data-access-plugin/job/PR-1215/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request closed without merging**
