### PR TITLE
[PPP-3685]-Cross-site scripting XSS vulnerability in DataSource name field

### PR DESCRIPTION
**Pull request by PashkovichAndrei**
Created input sanitizer method to escape special symbols

### CODE REVIEW

**Comment by PashkovichAndrei** [comment]
@mbatchelor, @pamval, could you please do review?

**Comment by PashkovichAndrei** [comment]
Solution need to be reworked. I'll send force update with a new solution.

**Comment by PashkovichAndrei** [comment]
@mchen-len-son, @mbatchelor, @pamval, could you please do review of a new solution?

**Comment by pamval** [comment]
@PashkovichAndrei, we're already using an encoding lbrary elsewhere. We should use that same library here. I think it's owasp but I'm not sure. @YuryBY probably remembers.

**Comment by PashkovichAndrei** [comment]
@pamval, it seems that I cannot use OWASP library at GWT code.
Basically, I reworked that solution using build-in GWT class [SafeHtmlUtils](http://www.gwtproject.org/javadoc/latest/com/google/gwt/safehtml/shared/SafeHtmlUtils.html)

Could you please do review again?

**Comment by PashkovichAndrei** [comment]
@mbatchelor, @pamval, could you please do review of a new solution?

**Comment by YuryBY** [comment]
@PashkovichAndrei here is auxiliary class in data-access that possibly can help here:

https://github.com/pentaho/data-access/blob/74534a68bcd20e369f523ee7d82165ce734285fe/core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/utils/UtilHtmlSanitizer.java

**Comment by PashkovichAndrei** [comment]
@mbatchelor, @pamval, could you please do review of a new solution?

**Pull request merged**
