### PR TITLE
BISERVER-12403

### PR DESCRIPTION
**Pull request by YuryBY**
@CodeOnCoffee would you mind to review/merge please
There are  two commits in PR:
1) Unit test 
2) Fix
Resume: fixEncodedSlashParam method was replacing slashes therefore path to metadata file had not been found. Now method is not called at all.

### CODE REVIEW

**Comment by TatsianaKasiankova** [comment]
@rmansoor 
Hi, please review this fix.

**Comment by rmansoor** [comment]
@YuryBY , @TatsianaKasiankova did you run the spira test for special characters. We need to ensure we can use special characters in a domain id.

**Comment by TatsianaKasiankova** [comment]
@rmansoor 
I'm able to add MetaData with "\" and "/" in Domain Id.
I've attached screens with such sources in the issue BISERVER-12403.
I'm not familiar spira with test sets. What spira test do you mean?

**Comment by rmansoor** [comment]
In  5.2 we added support for special character in the name of the file folder and datasources. For example {[]}()*&^%$~!@ are few examples to test the datasource with. Here is the spira test I was talking about http://spiratest.pentaho.com/6/TestCase/10956.aspx

**Comment by TatsianaKasiankova** [comment]
Thank you, starting checking.

**Comment by TatsianaKasiankova** [comment]
@rmansoor 
Verified Import MetaData with special characters in Domain Id (taken from http://spiratest.pentaho.com/6/TestCase/10956.aspx):
D-[~!@#$%^&*(){}|.,]-=_+|;'"?<>~`:
1.Imported successfully (see SpecialCharacters.png in BISERVER-12403)
2.Deleted successfully.

**Comment by rmansoor** [comment]
@TatsianaKasiankova this is looking good then. I am processing this pull request

**Pull request merged**
